# Generated by Django 5.0.6 on 2025-11-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_selection_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternative',
            options={'ordering': ['option']},
        ),
        migrations.RemoveConstraint(
            model_name='alternative',
            name='unique_question_option',
        ),
        migrations.AlterField(
            model_name='question',
            name='selection_type',
            field=models.CharField(choices=[('SINGLE', 'Única escolha'), ('MULTIPLE', 'Múltiplas escolhas')], db_index=True, default='SINGLE', help_text='Define se a questão aceita uma única resposta ou múltiplas.', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='alternative',
            unique_together={('question', 'option')},
        ),
    ]
